// <auto-generated />
using Alfreelina_P1_AP1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alfreelina_P1_AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201006002718_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Alfreelina_P1_AP1.Entidades.Ciudades", b =>
                {
                    b.Property<int>("CiudadesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("CiudadesID");

                    b.ToTable("Ciudades");
                });
#pragma warning restore 612, 618
        }
    }
}
